name: Deploy library

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish library
        env: 
          ACTION_USER_ID: "wottrichwarren"
          ACTION_PERSONAL_ACCESS_TOKEN: "91abb80532968a2bd61355308ea9b3806dac381c"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run gradle publish
        run: |
          gradle mylibrary:assemble
          gradle publish
      - name: Bump version and push tag
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
