name: Deploy library

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish library
        env: 
          ACTION_USER_ID: "wottrichwarren"
          ACTION_PERSONAL_ACCESS_TOKEN: "91abb80532968a2bd61355308ea9b3806dac381c"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run gradle publish
        run: |
          gradle mylibrary:assemble
          gradle publish
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/tag-${{ github.run_number }}(${{ github.run_id }})",
              sha: context.sha
            })
