name: Deploy library

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish library
        env: 
          ACTION_USER_ID: "oiwarren"
          ACTION_PERSONAL_ACCESS_TOKEN: $PERSONAL_ACCESS_TOKEN
        run: bash gradle:coreui-tokens:publish
