name: Workflow Dispatcher

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        run: |
          if [ 'true' = 'true' ] 
          then
            exit 0
          else
            exit 1
          fi
