name: Workflow Dispatcher

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
      #if [ 'false' = 'true' ] 
          #then
          #  exit 0
          #else
          #  exit 1
          #fi
        run: |
          echo "worked"
        id: conclusion_step
