name: Workflow Dispatcher

on:
  pull_request:
    branches: [ main ]
    
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        run: |
          echo "running"
